### ISSUE TITLE
Include a parameter for running in an iFrame

### ISSUE THREAD

**Issue by patrick-fs** [fullstorydev/fullstory-browser-sdk#1]
Per [this KB article](https://help.fullstory.com/using/recording-iframes), add a parameter to the init function that sets `window['_fs_run_in_iframe']`

**Comment by van-fs** [comment]
For completeness, we should also add `window['_fs_is_outer_script']`.

**Comment by patrick-fs** [comment]
@van-fs I'm thinking that we create a `IFrameOptions` enum that would look something like this:

```typescript
enum IFrameOption {
  SameDomainOnly,
  CrossDomainIFrame,
  OnlyInHostIFrame,
}
```

and then add this to the `SnippetOptions` interface:

```
interface SnippetOptions {
  orgId: string;
  namespace?: string;
  debug?: boolean;
  host?: string;
  script?: string;
  iFrameOption?: IFrameOption;
}
```
`window['_fs_run_in_iframe'] = true` if `iFrameOption == IFrameOption.CrossDomainIFrame`

and

`window['_fs_is_outer_script'] = true` if `iFrameOption == IFrameOption.OnlyInHostIFrame`

I can't see a reason why `window['_fs_run_in_iframe']  = window['_fs_is_outer_script'] = true` would be a valid statement, so we should be good to treat them as mutually exclusive switches.

**Comment by bddean** [comment]
The `_fs_run_in_iframe` flag actually isn't necessary for same-domain frames; it could be renamed to `_fs_run_in_crossdomain_frame`.

Aside: We should make sure that the IMPORTANT SECURITY NOTE from that KB article is communicated to users of this package. (We should really make this API more effortlessly secure!)

**Comment by patrick-fs** [comment]
> The `_fs_run_in_iframe` flag actually isn't necessary for same-domain frames; it could be renamed to `_fs_run_in_crossdomain_frame`.

Agreed.  `IFrameOption.CrossDomainIFrame` maps to `window['_fs_run_in_iframe'] = true`

> Aside: We should make sure that the IMPORTANT SECURITY NOTE from that KB article is communicated to users of this package. (We should really make this API more effortlessly secure!)

We could even console.warn :P maybe too heavy handed, but will def need to add security note if/when this feature is added. @bddean

**Comment by van-fs** [comment]
@patrick-fs can we push a fix for this?  We had a request come in.  LMK if you need me to make the change.

**Comment by patrick-fs** [comment]
@van-fs yes, go for it. Please assign me the PR.
