### ISSUE TITLE
Add a helper that checks to see if FullStory is already initiated

### ISSUE THREAD

**Issue by ralfstory** [fullstorydev/fullstory-browser-sdk#115]
This will help prevent reinitialization and reduce the subsequent noisy logs by being able to check the initialization status and calling FS.init conditionally.

**Comment by Iodine-** [comment]
I can't find anywhere in the docs where it says this specifically, but I have been using `window._fs_initialized` to do what you described

**Comment by ralfstory** [comment]
That definitely works!! Though I think it should be exposed through the SDK explicitly - the fact that you've also had a use case for this means it should probably be baked in!

**Comment by luser** [comment]
Fixed by #130.
