### ISSUE TITLE
getCurrentSessionURL with relay returns broken link

### ISSUE THREAD

**Issue by eni9889** [fullstorydev/fullstory-browser-sdk#119]
When using fullstory with full story relay the getCurrentSessionURL() returns `app.relay.domain` instead of `app.fullstory.com`

**Comment by patrick-fs** [comment]
Hi @eni9889 are you passing any config options into the `init()` function? If so, can you please share them here?

**Comment by eni9889** [comment]
> Hi @eni9889 are you passing any config options into the `init()` function? If so, can you please share them here?

Sure this is the init function: 

FullStory.init({
      orgId: environment.fullStoryOrg,
      recordCrossDomainIFrames: true,
      devMode: !environment.production,
      host: 'fsrelay.one.store',
      script: 'fsrelay.one.store/s/fs.js',
    })

**Comment by patrick-fs** [comment]
Hi @eni9889 thanks for the additional information.

There is a global parameter you can set on the `window` object that should explicitly set which domain is used by `getCurrentSessionURL()`

You can set it like this:

`window.fs_app_host = app.fullstory.com;`

We haven't yet incorporated this into the SDK init options, but this should global var should fix things for you. Please let me know if this doesn't work for you.
