### ISSUE TITLE
Release number alignment with HEAD release

### ISSUE THREAD

**Issue by billnbell** [fullstorydev/fullstory-browser-sdk#181]
Can you please update the github release number? It says 1.4.1 is the latest from 3 years ago, but your latest version is 1.7.1?

```
 "@fullstory/browser": "^1.7.1",
```

**Comment by patrick-fs** [comment]
Hey @billnbell good catch. We stopped using GitHub releases a while back. I can delete those releases to avoid confusion.

**Comment by patrick-fs** [comment]
releases have been deleted
