### ISSUE TITLE
Return type of FullStory("observe") is incorrect

### ISSUE THREAD

**Issue by benasher44** [fullstorydev/fullstory-browser-sdk#187]
`FullStory("observe", { type: "start", callback:… })` can return null it appears. We've seen a handful of errors in production calling `null.disconnect()`.

**Comment by rcmaples** [comment]
Hi @benasher44 — Thanks for calling this out. Do you mind to email support@fullstory.com? We'd like to dig in further and get some more information to help you get this sorted. You can reference this issue and we'll get this into the support engineering queue asap!

Thanks so much,
RC

**Comment by benasher44** [comment]
👍 ticket # is 227060

**Comment by benasher44** [comment]
From the support ticket, the answer is that observeAsync must be used to guarantee not getting null back. If that's the case, the observe's return type is indeed incorrect. I'll switch to using observeAsync, but the return type should probably be fixed.

**Comment by patrick-fs** [comment]
hey @benasher44 thanks for bringing this to our attention. We are indeed working on a fix for the return type. The team plans to deploy a patch in the new year. We'll close this ticket once the patch is live.

Have a great holiday and happy new year!

**Comment by benasher44** [comment]
Amazing thanks!
