### ISSUE TITLE
Usage with Rollup and Typescript

### ISSUE THREAD

**Issue by scefali** [fullstorydev/fullstory-browser-sdk#34]
I started converting the Sentry-FullStory integration into TS and I encountered this error

```yarn run v1.17.0
$ tsc src/index.ts && rollup -c
src/SentryFullStory.ts:3:8 - error TS1192: Module '"/Users/scefali/Work/sentry-fullstory/node_modules/@fullstorydev/browser/dist/index"' has no default export.

3 import FullStory from '@fullstorydev/browser';
```

Importing as such:
```
import FullStory from '@fullstorydev/browser';
```

EDIT:

I think changing the import is a workaround:
```
import * as FullStory from '@fullstorydev/browser';
```

**Comment by patrick-fs** [comment]
We'll make an update to address this. Right now, JS and TS clients import the API in two different ways:

JS ==> `import FullStory from '@fullstorydev/browser'`

TS ==> `import * as FullStory from '@fullstorydev/browser'`

Will make sure we provide a consistent interface.

**Comment by patrick-fs** [comment]
@scefali the latest PR should fix this issue - please verify.
