### ISSUE TITLE
CommonJS build

### ISSUE THREAD

**Issue by julienfouilhe** [fullstorydev/fullstory-browser-sdk#42]
Code is not compiled into CommonJS, therefore tools such as jest can not import the library without transforming it.

Could you provide a CommonJS build and change the package.json `main` attribute accordingly?

**Comment by htunnicliff** [comment]
I just added a PR for this in #43

**Comment by julienfouilhe** [comment]
Nice! cc @patrick-fs

**Comment by patrick-fs** [comment]
@julienfouilhe @htunnicliff the update is live. Thanks @htunnicliff ~
