### ISSUE TITLE
Cannot conditionally call init

### ISSUE THREAD

**Issue by rgpass** [fullstorydev/fullstory-browser-sdk#57]
I'm using this locally and I don't want local sessions to be sent up.

What I want to do is:

```js
if (process.env.NODE_ENV === 'production') {
  FullStory.init({ orgId: 'myOrgId });
}
```

But when I run another `FullStory` command, the app breaks. My guess is because [an error is thrown](https://github.com/fullstorydev/fullstory-browser-sdk/blob/master/src/index.js#L8) rather than a warning.

As a hacky workaround, I've had to do:

```js
const orgId = process.env.NODE_ENV === 'production' ? 'myOrgId' : 'aBunchOfRandomCharacters';
FullStory.init({ orgId });
```

**Comment by van-fs** [comment]
Hey @rgpass , thanks for bringing this up.  While we investigate, you can also use the domain whitelisting in FullStory to prevent local session recording.  Either set only the production FQDNs to allow recording or add the `localhost:port` to have recording `OFF`.  See [Can I disable recording for a specific domain?](https://help.fullstory.com/hc/en-us/articles/360020827533-Can-I-disable-recording-for-a-specific-domain-)

**Comment by patrick-fs** [comment]
@rgpass this is now live (https://github.com/fullstorydev/fullstory-browser-sdk/releases/tag/v1.4.0)

https://www.npmjs.com/package/@fullstory/browser
