### ISSUE TITLE
Error: FullStory is not loaded, please ensure the init function is invoked before calling FullStory API

### ISSUE THREAD

**Issue by sohinim98** [fullstorydev/fullstory-browser-sdk#79]
Sentry keeps throwing the `FullStory is not loaded, please ensure the init function is invoked before calling FullStory API` error.
This is an Angular2 app and I'm initializing FullStory from `app.component.ts` like this -
```
// fullStory analytics tracking
        FullStory.init({ orgId: environment.fullstoryOrgId,
          devMode: !environment.production });
        FullStory.identify(this.user._id, {
          displayName: this.user.name,
          email: this.user.email,
          institution: this.user.org_name,
        });
```

We have integrated Sentry with Fullstory using [@sentry/fullstory](https://www.npmjs.com/package/@sentry/fullstory) and we initialize sentry in a separate `entry-error-handler.ts` file and capture using `Sentry.captureException(error.originalError || error);`.

I tried checking if `FullStory.getCurrentSessionURL();` was ready before my `FullStory.identify` call and it wasn't meaning that FullStory wasn't fully bootstrapped. I also read that calls to FS.event can be made prior to bootstrapping and the only time we really need FullStory to be fully bootstrapped is for session replay url (or session replay id) which we're not using.

Since there isn't an `FullStory.OnReady()` function for FullStory, what's the suggested solution?

**Comment by van-fs** [comment]
Hi @sohinim98 , thanks for opening your issue.  There is the concept of [_fs_ready](https://developer.fullstory.com/callbacks-and-delegates), but I don't think that's the nature of this particular issue.  You're right, the call to `FullStory.init()` is synchronous, and any subsequent calls like your `FullStory.identify` usage is valid.  The APIs will be stubbed out until the recording code is fetched and bootstrapped.  I'm curious about your statement:

> we initialize sentry in a separate entry-error-handler.ts file

Are you referring to the [ErrorHandler](https://angular.io/api/core/ErrorHandler) hook in Angular?  If so, this hook is executed when `app.module` is evaluated and before `app.component.ts`'s constructor.  I'm wondering if the code in the ErrorHandler is registering Sentry and is indeed calling `FullStory` before it's `init`ed.  Can you provide a bit more detail about the ErrorHandler and when `FullStory.init` is called within `app.component.ts`?  This feels like a timing issue between `FullStory` and `Sentry` SDKs.

**Comment by sohinim98** [comment]
Yes, that's exactly right. SentryErrorHandler is hooked as an [ErrorHandler](https://angular.io/api/core/ErrorHandler) and executed when when `app.module.ts` is evaluated which is before `app.component.ts`'s constructor. Thanks for identifying the issue.

I'm calling `FullStory.init` in `app.component.ts`'s constructor. I execute `this.subscribers.push` and call the userService to get the current user's details from the BE, and then init FullStory, so it's along the lines of this -

```
constructor(//...services) {
   this.subscribers.push(this.userService.user.subscribe(res => {
   this.user = res && res.user;
   if (this.user.blah) {
      // some more code
   }
   if (this.user && this.user._id) {
   // fullStory analytics tracking
        FullStory.init({ orgId: environment.fullstoryOrgId,
          devMode: !environment.production });
        FullStory.identify(this.user._id, {
          displayName: this.user.name,
          email: this.user.email,
          institution: this.user.org_name,
        });
      }
}));
}
```

**Comment by van-fs** [comment]
I have an inquiry into Sentry to see if there's a way to "lazy load" the FullStory integration.  In the meantime, I _think_ you could simply add the `FullStory.init` outside the `AppComponent` class.  What I expect to happen is that as long as the `FullStory.init` is evaluated before the `ErrorHandler`, then the error should not occur.  You could move this:

```javascript
FullStory.init({ orgId: environment.fullstoryOrgId,
          devMode: !environment.production });
```

into `main.ts` for example.

`FullStory.identify` can remain in your `AppComponent`'s constructor as you have it today.  It might feel a little non-standard, but I don't think there's any functional issue.  Often we suggest to load FullStory as early as possible in the `<head>` tag.  With this change, you're just moving the evaluation earlier.  Let us know if that provides some help.

**Comment by patrick-fs** [comment]
@sohinim98 did moving the FullStory `init` invocation into `main.ts` solve your problem?

**Comment by sohinim98** [comment]
Yes, it did. @patrick-fs

**Comment by patrick-fs** [comment]
Great! I'm going to close this issue. Thanks for reaching out to us.
