### ISSUE TITLE
GET https://edge.fullstory.com/s/fs.js net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by davidfloegel** [fullstorydev/fullstory-browser-sdk#83]
Hi there,

I've started using this module and followed all the instructions, but when I actually visit my page I receive:
```
GET https://edge.fullstory.com/s/fs.js net::ERR_BLOCKED_BY_CLIENT
```

This happens locally (localhost:4200) as well as an my staging site.

Any ideas what might be wrong?

Thanks!

**Comment by Obi-Dann** [comment]
@davidfloegel are you using adblock or uBlock or any other ad blocking extensions? Some of them consider fullstory a tracker and disable it by default.

**Comment by patrick-fs** [comment]
HI @kirkas apologies for the delayed replay. We don't plan on making `fs.js` part of the SDK.

I'm going to close this issue since the original question has been answered.

Thanks all.
