### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by Lilja** [fullstorydev/fullstory-browser-sdk#84]
Hi!

I was wondering if this SDK has support for vue 3. I can't seem to find any references to it in any github issue so I figured i'd start one.

This is in the main readme:

```JavaScript
import Vue from 'vue';
import App from './App.vue';
import * as FullStory from '@fullstory/browser';

FullStory.init({ orgId: '<your org id here>' });
Vue.prototype.$FullStory = FullStory;

new Vue({
  render: h => h(App)
}).$mount('#app');
```

As of vue 3, vue changes a few things like `new Vue()` -> `createApp`, which you import as `import {createApp} from 'vue'`. I don't think `Vue.prototype` is a thing anymore either.

**Comment by sabrina-li** [comment]
Hey @Lilja, 
Thanks for bring this up! 
Vue 3 has [replaced `Vue.prototype` with `config.globalProperties`](https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties)
Here's a PR adding Vue 3 code samples: https://github.com/fullstorydev/fullstory-browser-sdk/pull/85 
```javascript
import { createApp } from 'vue'
import App from './App.vue'
import * as FullStory from '@fullstory/browser';

FullStory.init({ orgId: '<your org id here>' });

const app = createApp(App);
app.config.globalProperties.$FullStory = FullStory;
app.mount('#app');
```
Thank you!
